name: aws_sdk
description: A starting point for Dart libraries or applications.
version: 0.0.2
homepage: https://github.com/TylerSustare/aws_sdk

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
